// <auto-generated />
using System;
using CurilClever2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurilClever2.Migrations
{
    [DbContext(typeof(CleverDBContext))]
    [Migration("20190227175634_Comments2")]
    partial class Comments2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CurilClever2.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("PassportData");

                    b.Property<string>("Phone");

                    b.Property<string>("SecondName");

                    b.Property<int>("Sex");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CurilClever2.Models.ClientComment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<int?>("Commentid");

                    b.Property<int>("CommetId");

                    b.HasKey("id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Commentid");

                    b.ToTable("ClientComments");
                });

            modelBuilder.Entity("CurilClever2.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Posted");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CurilClever2.Models.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres");

                    b.Property<int>("LocationType");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("StarsRate");

                    b.HasKey("id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("CurilClever2.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginTravelDate");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<DateTime>("EndTravelDate");

                    b.Property<int>("HoteId");

                    b.Property<int?>("Hotelid");

                    b.HasKey("id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Hotelid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CurilClever2.Models.OrderComment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Commentid");

                    b.Property<int>("CommetId");

                    b.Property<int>("OrderId");

                    b.HasKey("id");

                    b.HasIndex("Commentid");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderComments");
                });

            modelBuilder.Entity("CurilClever2.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("accessLevel");

                    b.Property<string>("name");

                    b.Property<string>("passwordHash");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CurilClever2.Models.ClientComment", b =>
                {
                    b.HasOne("CurilClever2.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CurilClever2.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("Commentid");
                });

            modelBuilder.Entity("CurilClever2.Models.Comment", b =>
                {
                    b.HasOne("CurilClever2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CurilClever2.Models.Order", b =>
                {
                    b.HasOne("CurilClever2.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CurilClever2.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("Hotelid");
                });

            modelBuilder.Entity("CurilClever2.Models.OrderComment", b =>
                {
                    b.HasOne("CurilClever2.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("Commentid");

                    b.HasOne("CurilClever2.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
